spring.application.name=devvault

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/devvault}
spring.datasource.username=${DB_USERNAME:devvault_app}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=true

server.port=8080